### PR TITLE
Update recipe to AGL funky flounder(FF)

### PR DESCRIPTION
**Pull request by RyoKodama**

### CODE REVIEW

**Comment by dhobsong** [comment]
Kodama-san,

Thank you for the PR. Before I merge this I just want to double-check whether this patch is still necessary for gstreamer 1.12.  Once I confirm that I will either merge or close this.

**Comment by dhobsong** [comment]
Kurokawa-san, 

This PR looks ok as is, but I'm trying to test it and I can't find a FF branch for meta-renesas-rcar-gen3 on AGL, and the eel branch is using GStreamer 1.6.3.  Can you please tell me which branch/manifest you tested this with? Thanks.

**Comment by RyoKodama** [comment]
Damian-san

I used FF-rc2 bellow.
https://wiki.automotivelinux.org/agl-distro/release-notes#flounder_600_rc2
Using this repo, you can see following branch on meta-renesas-rca-gen3 which includes gstreamer 1.12.2.

=================================================================
commit 9e674d57e534c23834528bfdfc0725641f7f8df6 (tag: flounder_5.99.2, tag: flounder/5.99.2, tag: 5.99.2, tag: m/master, agl/master)
Author: Ronan Le Martret <ronan.lemartret@iot.bzh>
Date:   Tue Jul 10 15:12:14 2018 +0200

    [COMMUNITY] Rename recipes to be compliant with poky
    
    * Using '%' instead of the current version of the recipes
      is a better compliance with yocto standart
    
    Bug-AGL: SPEC-1581
    
    Change-Id: I7813d3bfa0a2514b4ad0e6819881dd9f632823fb
    Signed-off-by: Ronan Le Martret <ronan.lemartret@iot.bzh>
=================================================================

Does it make sense?

**Comment by dhobsong** [comment]
Kodama-san,

Yes, its perfect. I am building it now. 

PS. Sorry I mistakenly put Kurokawa-san's name on my last comment. It meant to write Kodama-san.

**Comment by RyoKodama** [comment]
No problem!
I'm looking forward to get your approval.

**Pull request merged**
