### PR TITLE
update for 67.0.3375.0.r543955

### PR DESCRIPTION
**Pull request by RyoKodama**
I tried to update this recipe for the latest chromium.
I confirmed running VDA on AGL EE-5.0.2.

### CODE REVIEW

**Comment by dhobsong** [comment]
Kodama-san,

I'm sorry that I didn't get back to you about this MR sooner. I only noticed it last week.  I am building EE right now and if there are no problems, hope to test and merge this early next week.

**Comment by RyoKodama** [comment]
Damian-san

It's alright. I've almost forgotten about this even though I.
And I realized this pull request is outdated.
Can you delete this pull request?
I'll make a new pull request.

**Comment by RyoKodama** [comment]
I fixed commit message a little.

**Comment by RyoKodama** [comment]
I also made a branch for AGL FF(funky flounder).
Can you make another branch?
I'll make pull request of FF as well.

**Comment by dhobsong** [comment]
@RyoKodama Thank you for the updated patch. The second patch "add the patch resolving crash end of a movie" is reverted by the third "Update v4l-gst patch for AGL eel branch", so its better to just squash these two into one patch that just updates the branch and SRCREV.

I will create the FF branch for your PR

**Comment by RyoKodama** [comment]
Thank you for the reviewing.
That's right. It was verbose. I fixed the patch. Does it make sense?

**Comment by RyoKodama** [comment]
I fixed the commit message.

**Comment by dhobsong** [comment]
@RyoKodama The SRCREV setting for v4l-gst.bb has disappeared from the latest patch.  Is that intentional?

**Comment by RyoKodama** [comment]
@dhobsong Sorry I've just forgotten. I fixed it.

**Pull request merged**
